# Generated by Django 5.2.16 on 2026-08-11 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0006_pricingrule_occupancy_threshold_and_more'),
        ('tenants', '0003_backfill_default_hotel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('category', models.CharField(choices=[('minibar', 'Minibar'), ('linen', 'Linge'), ('supplies', 'Fournitures'), ('cleaning', "Produits d'entretien"), ('other', 'Autre')], default='supplies', max_length=20)),
                ('unit', models.CharField(choices=[('piece', 'Pièce'), ('kg', 'Kilogramme'), ('l', 'Litre'), ('pack', 'Paquet')], default='piece', max_length=10)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité en stock')),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Seuil d'alerte")),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût unitaire (FCFA)')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='tenants.hotel')),
            ],
            options={
                'verbose_name': 'Article en stock',
                'verbose_name_plural': 'Articles en stock',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('movement_type', models.CharField(choices=[('in', 'Entrée (achat/réassort)'), ('out', 'Sortie (consommation)'), ('adjustment', 'Ajustement (inventaire)'), ('loss', 'Perte / casse')], max_length=12)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='tenants.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='rooms.room', verbose_name='Chambre (minibar)')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
