# Generated by Django 5.2.16 on 2026-08-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenants', '0003_backfill_default_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['category__name', 'name'], 'verbose_name': 'Article en stock', 'verbose_name_plural': 'Articles en stock'},
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('icon', models.CharField(default='bi-box-seam', max_length=40, verbose_name='Icône (classe Bootstrap Icons)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='tenants.hotel')),
            ],
            options={
                'verbose_name': 'Catégorie de stock',
                'verbose_name_plural': 'Catégories de stock',
                'ordering': ['name'],
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorycategory', verbose_name='Catégorie'),
        ),
    ]
