# Generated by Django 5.2.16 on 2026-08-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_seed_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventoryitem'),
        ),
    ]
