# Generated by Django 5.1.4 on 2026-06-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de base (FCFA)')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Capacité (personnes)')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='Équipements')),
            ],
            options={
                'verbose_name': 'Type de chambre',
                'verbose_name_plural': 'Types de chambres',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Numéro')),
                ('floor', models.IntegerField(choices=[(0, 'Rez-de-chaussée'), (1, '1er étage'), (2, '2ème étage'), (3, '3ème étage'), (4, '4ème étage')], default=0, verbose_name='Étage')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupée'), ('maintenance', 'En maintenance'), ('cleaning', 'En nettoyage')], default='available', max_length=20, verbose_name='Statut')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix personnalisé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['number'],
            },
        ),
    ]
