# Generated by Django 5.1.4 on 2026-06-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la règle')),
                ('rule_type', models.CharField(choices=[('season_high', 'Saison haute'), ('season_low', 'Saison basse'), ('weekend', 'Weekend'), ('early_bird', 'Réservation anticipée'), ('last_minute', 'Last minute')], max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('percent_change', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Variation en % (négatif = réduction)')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Date début (saisons)')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Date fin (saisons)')),
                ('days_threshold', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seuil en jours (early_bird / last_minute)')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Priorité (plus grand = prioritaire)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='rooms.roomtype', verbose_name='Type de chambre (optionnel)')),
            ],
            options={
                'verbose_name': 'Règle de tarification',
                'verbose_name_plural': 'Règles de tarification',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
