# Generated by Django 5.1.4 on 2026-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_pricingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarif horaire (FCFA)'),
        ),
    ]
