# Generated by Django 5.1.4 on 2026-07-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_hotel_fk'),
        ('rooms', '0003_roomtype_hourly_rate'),
    ]

    operations = [
    ]
