# Generated by Django 5.2.15 on 2026-08-11 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_merge_0002_hotel_fk_0003_roomtype_hourly_rate'),
        ('tenants', '0002_alter_hotel_email_alter_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='tenants.hotel'),
        ),
    ]
