# Generated by Django 5.2.16 on 2026-08-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_pricingrule_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='occupancy_threshold',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Seuil de taux d'occupation en % (occupancy)"),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('season_high', 'Saison haute'), ('season_low', 'Saison basse'), ('weekend', 'Weekend'), ('early_bird', 'Réservation anticipée'), ('last_minute', 'Last minute'), ('occupancy', "Taux d'occupation")], max_length=20, verbose_name='Type'),
        ),
    ]
