# Generated by Django 5.1.4 on 2026-06-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Référence')),
                ('check_in', models.DateField(verbose_name="Date d'arrivée")),
                ('check_out', models.DateField(verbose_name='Date de départ')),
                ('adults', models.PositiveIntegerField(default=1, verbose_name='Adultes')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Enfants')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('checked_in', 'En cours (Check-in)'), ('checked_out', 'Terminée (Check-out)'), ('cancelled', 'Annulée'), ('no_show', 'No-show')], default='pending', max_length=20, verbose_name='Statut')),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('phone', 'Téléphone'), ('online', 'En ligne'), ('agency', 'Agence')], default='direct', max_length=20, verbose_name='Source')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par nuit (FCFA)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix total (FCFA)')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Acompte (FCFA)')),
                ('special_requests', models.TextField(blank=True, verbose_name='Demandes spéciales')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='clients.client', verbose_name='Client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
