# Generated by Django 5.1.4 on 2026-06-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('clients', '0003_alter_client_vip_status_and_more'),
        ('rooms', '0002_pricingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(db_index=True, verbose_name="Date d'arrivée"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(db_index=True, verbose_name='Date de départ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('checked_in', 'En cours (Check-in)'), ('checked_out', 'Terminée (Check-out)'), ('cancelled', 'Annulée'), ('no_show', 'No-show')], db_index=True, default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'check_in', 'check_out'], name='booking_room_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status'], name='booking_client_status_idx'),
        ),
    ]
