# Generated by Django 5.1.4 on 2026-06-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_check_in_alter_booking_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acompte encaissé le'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Acompte demandé (FCFA)'),
        ),
    ]
