# Generated by Django 5.1.4 on 2026-06-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_deposit_paid_at_alter_booking_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Restauration'), ('transport', 'Transport'), ('spa', 'Spa & Bien-être'), ('laundry', 'Blanchisserie'), ('minibar', 'Minibar'), ('phone', 'Téléphone'), ('other', 'Autre')], default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Service extra',
                'verbose_name_plural': 'Services extras',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
