# Generated by Django 5.1.4 on 2026-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_extra_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='billing_type',
            field=models.CharField(choices=[('nightly', 'Nuit(s)'), ('hourly', 'Heure(s)')], default='nightly', max_length=10, verbose_name='Facturation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée (heures)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix par heure (FCFA)'),
        ),
    ]
