# Generated by Django 5.1.4 on 2026-07-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_hotel_fk'),
        ('bookings', '0005_booking_billing_type_booking_hours_and_more'),
    ]

    operations = [
    ]
