# Generated by Django 5.2.16 on 2026-08-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_merge_20260701_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('on_site', 'Sur place'), ('transfer', 'Virement bancaire')], default='on_site', max_length=20, verbose_name='Mode de paiement souhaité'),
        ),
    ]
