# Generated by Django 5.1.4 on 2026-06-25 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_alter_booking_check_in_alter_booking_check_out_and_more'),
        ('rooms', '0002_pricingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'À nettoyer'), ('in_progress', 'En cours'), ('done', 'Terminé'), ('inspected', 'Inspecté')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priorité')),
                ('notes', models.TextField(blank=True, verbose_name='Consignes')),
                ('scheduled_for', models.DateField(blank=True, null=True, verbose_name='Prévue le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='bookings.booking', verbose_name='Réservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to='rooms.room', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Tâche de nettoyage',
                'verbose_name_plural': 'Tâches de nettoyage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='cleaning_status_date_idx')],
            },
        ),
    ]
