# Generated by Django 5.1.4 on 2026-06-25 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking_deposit_paid_at_alter_booking_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('room_revenue', 'Revenus chambres'), ('deposit', 'Acomptes encaissés'), ('extra', 'Services extra'), ('other_income', 'Autres recettes'), ('staff', 'Personnel'), ('maintenance', 'Maintenance'), ('supplies', 'Fournitures'), ('utilities', 'Charges & Fluides'), ('marketing', 'Marketing'), ('taxes', 'Impôts & Taxes'), ('other_expense', 'Autres dépenses')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(db_index=True)),
                ('description', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile', 'Mobile Money'), ('transfer', 'Virement'), ('other', 'Autre')], default='cash', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['type', 'date'], name='accounting__type_51c308_idx'), models.Index(fields=['category', 'date'], name='accounting__categor_0935c3_idx')],
            },
        ),
    ]
