# Generated by Django 5.1.4 on 2026-06-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('room_revenue', 'Revenus chambres'), ('deposit', 'Acomptes encaissés'), ('extra', 'Services extra'), ('other_income', 'Autres recettes'), ('staff', 'Personnel'), ('maintenance', 'Maintenance'), ('supplies', 'Fournitures'), ('utilities', 'Charges & Fluides'), ('marketing', 'Marketing'), ('taxes', 'Impôts & Taxes'), ('other_expense', 'Autres dépenses')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant budget (FCFA)')),
                ('period', models.CharField(choices=[('monthly', 'Mensuel'), ('annual', 'Annuel')], default='monthly', max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alert_pct', models.PositiveSmallIntegerField(default=80, verbose_name='Alerte à (%) du budget')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['year', 'month', 'category'],
                'unique_together': {('category', 'period', 'year', 'month')},
            },
        ),
    ]
