# Generated by Django 5.2.15 on 2026-08-11 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_budget'),
        ('tenants', '0002_alter_hotel_email_alter_hotel_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='tenants.hotel'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('hotel', 'category', 'period', 'year', 'month')},
        ),
    ]
