# Generated by Django 5.1.4 on 2026-06-25 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking_deposit_paid_at_alter_booking_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Jeton de réponse')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('score_overall', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Note globale')),
                ('score_cleanliness', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Propreté')),
                ('score_service', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Service')),
                ('score_comfort', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Confort')),
                ('score_value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rapport qualité/prix')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('would_return', models.BooleanField(blank=True, null=True, verbose_name='Reviendrait')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='bookings.booking', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Questionnaire de satisfaction',
                'verbose_name_plural': 'Questionnaires de satisfaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
