# Generated by Django 5.2.16 on 2026-08-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_fix_services_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='video_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='video_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
