# Generated by Django 5.1.4 on 2026-06-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émise'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'émission")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile', 'Mobile Money'), ('transfer', 'Virement'), ('other', 'Autre')], max_length=20, verbose_name='Mode de paiement')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sous-total (FCFA)')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxes (FCFA)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('extra_services', models.JSONField(blank=True, default=list, verbose_name='Services supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='bookings.booking', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
    ]
