# Generated by Django 5.2.15 on 2026-08-11 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment'),
        ('tenants', '0002_alter_hotel_email_alter_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.hotel'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émise'), ('paid', 'Payée'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=20, verbose_name='Statut'),
        ),
    ]
