# Generated by Django 5.2.16 on 2026-08-27 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0007_booking_payment_method'),
        ('rooms', '0006_pricingrule_occupancy_threshold_and_more'),
        ('tenants', '0003_backfill_default_hotel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RfidCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=64, verbose_name='Identifiant carte')),
                ('card_type', models.CharField(choices=[('guest', 'Client'), ('staff', 'Personnel'), ('master', 'Passe général')], default='guest', max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('lost', 'Perdue')], db_index=True, default='active', max_length=10, verbose_name='Statut')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valide à partir de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name="Valide jusqu'à")),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_cards', to='bookings.booking', verbose_name='Réservation')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_cards', to='tenants.hotel')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_cards_issued', to=settings.AUTH_USER_MODEL, verbose_name='Émise par')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_cards', to='rooms.room', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Carte RFID',
                'verbose_name_plural': 'Cartes RFID',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'uid'], name='rfid_rfidca_hotel_i_dfff32_idx'), models.Index(fields=['hotel', 'status'], name='rfid_rfidca_hotel_i_1bcc6e_idx')],
            },
        ),
    ]
