# Generated by Django 5.1.4 on 2026-06-25 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_pricingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Emplacement (si pas une chambre)')),
                ('category', models.CharField(choices=[('plumbing', 'Plomberie'), ('electrical', 'Électricité'), ('hvac', 'Climatisation / Chauffage'), ('furniture', 'Mobilier'), ('cleaning', 'Nettoyage spécial'), ('painting', 'Peinture'), ('it', 'Informatique / TV'), ('security', 'Sécurité'), ('other', 'Autre')], default='other', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], db_index=True, default='open', max_length=15)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût (FCFA)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notes de résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='rooms.room', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Ticket de maintenance',
                'verbose_name_plural': 'Tickets de maintenance',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='ticket_status_priority_idx')],
            },
        ),
    ]
