# Generated by Django 5.1.4 on 2026-06-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('specialty', models.CharField(choices=[('plumbing', 'Plomberie'), ('electrical', 'Électricité'), ('hvac', 'Climatisation / Chauffage'), ('furniture', 'Mobilier'), ('cleaning', 'Nettoyage spécial'), ('painting', 'Peinture'), ('it', 'Informatique / TV'), ('security', 'Sécurité'), ('general', "Général (tous corps d'état)"), ('other', 'Autre')], default='other', max_length=30, verbose_name='Spécialité')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Entreprise')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Technicien',
                'verbose_name_plural': 'Techniciens',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='maintenance.technician', verbose_name='Technicien'),
        ),
    ]
