# Generated by Django 5.2.15 on 2026-08-11 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_technician_model'),
        ('tenants', '0002_alter_hotel_email_alter_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='tenants.hotel'),
        ),
        migrations.AddField(
            model_name='technician',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='tenants.hotel'),
        ),
    ]
