# Generated by Django 5.2.16 on 2026-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenanceticket_hotel_technician_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plomberie'), ('electrical', 'Électricité'), ('hvac', 'Climatisation / Chauffage'), ('furniture', 'Mobilier'), ('cleaning', 'Nettoyage spécial'), ('painting', 'Peinture'), ('it', 'Informatique / TV'), ('security', 'Sécurité'), ('other', 'Autre')], default='other', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], db_index=True, default='medium', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], db_index=True, default='open', max_length=15, verbose_name='Statut'),
        ),
    ]
