# Generated by Django 5.2.16 on 2026-08-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenanceticket_category_and_more'),
        ('rooms', '0006_pricingrule_occupancy_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='rooms.room', verbose_name='Chambre'),
        ),
    ]
