# Generated by Django 5.1.4 on 2026-07-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar'),
        ('accounts', '0002_user_hotel'),
    ]

    operations = [
    ]
