# Generated by Django 5.1.4 on 2026-06-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('id_type', models.CharField(choices=[('cni', "Carte Nationale d'Identité"), ('passport', 'Passeport'), ('driver', 'Permis de conduire'), ('other', 'Autre')], default='cni', max_length=20, verbose_name="Type de pièce d'identité")),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de pièce')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
