# Generated by Django 5.1.4 on 2026-06-25 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='client',
            name='preferences',
            field=models.TextField(blank=True, verbose_name='Préférences'),
        ),
        migrations.AddField(
            model_name='client',
            name='vip_status',
            field=models.CharField(choices=[('regular', 'Régulier'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='regular', max_length=10, verbose_name='Statut VIP'),
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('note', 'Note interne'), ('call', 'Appel téléphonique'), ('email', 'Email'), ('complaint', 'Réclamation'), ('request', 'Demande spéciale'), ('visit', 'Visite / Séjour')], default='note', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_notes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
