# Generated by Django 5.1.4 on 2026-06-25 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_birthday_client_preferences_client_vip_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='vip_status',
            field=models.CharField(choices=[('regular', 'Régulier'), ('vip', 'VIP'), ('vvip', 'VVIP')], db_index=True, default='regular', max_length=10, verbose_name='Statut VIP'),
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['client', '-created_at'], name='clientnote_client_date_idx'),
        ),
    ]
