# Generated by Django 5.1.4 on 2026-06-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_vip_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='blacklist_reason',
            field=models.TextField(blank=True, verbose_name='Motif liste noire'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_blacklisted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Liste noire'),
        ),
    ]
