# Generated by Django 5.1.4 on 2026-07-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_hotel_fk'),
        ('clients', '0004_blacklist_fields'),
    ]

    operations = [
    ]
