# Generated by Django 5.2.16 on 2026-08-27 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_merge_0002_hotel_fk_0004_blacklist_fields'),
        ('tenants', '0003_backfill_default_hotel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(choices=[('restaurant', 'Restaurant'), ('conference', 'Salle de conférence'), ('pool', 'Piscine'), ('spa', 'Spa')], db_index=True, max_length=20, verbose_name='Service')),
                ('client_name', models.CharField(max_length=150, verbose_name='Nom du client')),
                ('client_phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('party_size', models.PositiveIntegerField(default=1, verbose_name='Nombre de personnes')),
                ('detail', models.CharField(blank=True, max_length=150, verbose_name='Détail')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenity_reservations', to='clients.client', verbose_name='Client (fiche existante)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenity_reservations_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenity_reservations', to='tenants.hotel')),
            ],
            options={
                'verbose_name': 'Réservation de service',
                'verbose_name_plural': 'Réservations de services',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['amenity', 'date'], name='amenities_a_amenity_471927_idx')],
            },
        ),
    ]
