# Generated by Django 5.2.16 on 2026-08-28 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
        ('tenants', '0003_backfill_default_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenityreservation',
            name='source',
            field=models.CharField(choices=[('staff', 'Personnel'), ('online', 'En ligne')], default='staff', max_length=10),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du plat')),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('starter', 'Entrée'), ('main', 'Plat principal'), ('dessert', 'Dessert'), ('drink', 'Boisson')], default='main', max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Au menu du jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='tenants.hotel')),
            ],
            options={
                'verbose_name': 'Plat du menu',
                'verbose_name_plural': 'Plats du menu',
                'ordering': ['category', 'name'],
            },
        ),
    ]
