# Generated by Django 5.2.15 on 2026-08-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(help_text='Email du responsable / compte de facturation', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
