# Generated by Django 5.2.16 on 2026-08-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_hotel_and_rename(apps, schema_editor):
    AuditEntry = apps.get_model('audit_log', 'AuditEntry')
    AuditEntry.objects.filter(model_name='User').update(model_name='Utilisateur')
    for entry in AuditEntry.objects.select_related('user').filter(hotel__isnull=True, user__isnull=False):
        if entry.user.hotel_id:
            entry.hotel_id = entry.user.hotel_id
            entry.save(update_fields=['hotel'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
        ('tenants', '0003_backfill_default_hotel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='Champs modifiés : {champ: [avant, après]} ou snapshot à la suppression'),
        ),
        migrations.AddField(
            model_name='auditentry',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='tenants.hotel'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['hotel', '-created_at'], name='audit_log_a_hotel_i_bd873d_idx'),
        ),
        migrations.RunPython(backfill_hotel_and_rename, noop),
    ]
