# Generated by Django 5.2.16 on 2026-08-27 20:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0003_alter_auditentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='changes',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Champs modifiés : {champ: [avant, après]} ou snapshot à la suppression'),
        ),
    ]
