# Generated by Django 5.2.16 on 2026-08-11 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_backfill_default_hotel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('position', models.CharField(choices=[('reception', 'Réception'), ('housekeeping', 'Ménage'), ('maintenance', 'Maintenance'), ('restaurant', 'Restauration'), ('management', 'Direction'), ('security', 'Sécurité'), ('other', 'Autre')], default='other', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='tenants.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Créneau de travail',
                'verbose_name_plural': 'Créneaux de travail',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'user'], name='scheduling__date_c8a4f5_idx')],
            },
        ),
    ]
